### ISSUE TITLE
How to generate style without a class ?

### ISSUE THREAD

**Issue by tyrcho** [japgolly/scalacss#129]
I'm trying to generate inline stylesheet (to use with scalaJS) to replace my current css file with this content, is this possible with scalaCSS ? I spent some time to search for such examples but could not find any ...

```css
@media all and (min-width: 800px) {
    * {
        font-size: 4vmin;
    }
}

* {
    box-sizing: border-box;
}

body {
    margin: 1vmin;
}
```
