### ISSUE TITLE
Generating wrong css for :after :before pseudo selectors

### ISSUE THREAD

**Issue by chandu0101** [japgolly/scalacss#45]
```scala
 val reactTreeView = style(
       &.before.after(
        content := "g"
       )
    )
```

producing 

```css
.ReactTreeView_DefaultStyle-0001::after::before {
  content: g;
}
```

adding ``::`` instead of ``:``
