### ISSUE TITLE
Media queries always on top?

### ISSUE THREAD

**Issue by cretz** [japgolly/scalacss#47]
I am trying to mimic some CSS in the wild that looks like this:

```css
.main {
  padding: 20px;
}
@media (min-width: 768px) {
  .main {
    padding-right: 40px;
    padding-left: 40px;
  }
}
```

When in this order, browsers respect all values, but if the media queries are above, then they are not respected and they get overridden. So when I write a direct translation like:

```scala
  ".main" - (
    padding(20 px),
    &(media.minWidth(768 px)) - (
      paddingRight(40 px),
      paddingLeft(40 px)
    )
  )
```
It puts the media queries up top. I can't even break apart the rules to keep the media queries from going to the top. And even when I write this:

```scala
  ".main" - padding(20 px)

  "@media (min-width: 768px)" - (
    &(".main") - (
      paddingRight(40 px),
      paddingLeft(40 px)
    )
  )
```

I get:

```css
.main {
  padding: 20px;
}

@media (min-width: 768px) .main {
  padding-right: 40px;
  padding-left: 40px;
}
```

Which is not the same as having ``.main`` nested inside. Any ideas on how to achieve my goal?

**Comment by japgolly** [comment]
The implicit `Render[String]` in the Defaults does that.
https://github.com/japgolly/scalacss/blob/master/core/src/main/scala/scalacss/Renderer.scala#L26-L29

For now you could write your own implicit `Render[String]` that does that bit differently.

More permanently, do you think we should change the defaults to always put MQs at the bottom instead of the top?

**Comment by cretz** [comment]
I would suggest that the order they are in the code should be the determining factor.

**Comment by cretz** [comment]
Also, for the latter problem, how can I generate this:

```css
@media (min-width: 768px) {
  .main {
    padding-right: 40px;
    padding-left: 40px;
  }
}
```

I can't find a way to generate that (regardless of order). Sorry to couple problems into a single issue.
