### ISSUE TITLE
order of media queries?

### ISSUE THREAD

**Issue by chandu0101** [japgolly/scalacss#52]
```scala
val test = style(display.flex,
      flexDirection.column,
      boxShadow := "0 1px 3px 0 rgba(0, 0, 0, 0.12), 0 1px 2px 0 rgba(0, 0, 0, 0.24)",
      media.maxWidth(740 px)(
        boxShadow := "none"
       )
      )
```
its generating media 

```css
@media (max-width:740px) {
  .Test_Style-0002 {
    -webkit-box-shadow: none;
    box-shadow: none;
  }
.Test_Style-0002 {
  display: -webkit-flex;
  display: flex;
  -webkit-flex-direction: column;
  flex-direction: column;
  -webkit-box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.12), 0 1px 2px 0 rgba(0, 0, 0, 0.24);
  box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.12), 0 1px 2px 0 rgba(0, 0, 0, 0.24);
}
```

if media query is on top box-shadow is not overriden .

Here is codepen to demonstrate this (move media query to bottom and resize window)
http://codepen.io/chandu0101/pen/MwEoNY
