### ISSUE TITLE
How to refer to a StyleA?

### ISSUE THREAD

**Issue by wenLiangcan** [japgolly/scalacss#82]
How can I implement the CSS code below in ScalaCSS? 

```css
li:hover .item {
	display: block;
}
```

```scala

val item = style(
    display.none,
    /* ... */
)

val liStyle = style(
    &.hover(/* How to select `item` ? */)
)
```

Thanks in advanced!

**Comment by bpatters** [comment]
I'm curious about this too, haven't figured out to show an item when you hover on a parent item.

**Comment by nkgm** [comment]
```scala
val liStyle = style(
  &.hover(
    unsafeChild(".item")(
      display.block
    )
  )
)
```
would give:
```css
.XYZ_Style-liStyle:hover .item {
  display: block;
}
```
BTW is it possible to customise the `.XYZ_Style` portion of the selector @japgolly?
